name = "in"
version = "1.1.0"

description = "A small Gleam package that provides input functions (stdin reading) missing from gleam/io."
licences = ["Apache-2.0"]
repository = { type = "github", user = "evanlua", repo = "in" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"